version: '2'

services:
    mysql-service:
        build: ./mysql
        restart: always
        environment:
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USERNAME}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        volumes:
            - ${BASE_DATABASE_PATH}/data/mysql/dev-trial:/var/lib/mysql
        ports:
            - 3306:3306

    webserver:
        build: .
        restart: always
        volumes:
            - ./src:/var/www/html
        environment:
            DATABASE_HOST: "mysql-service"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USERNAME}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports:
            - 8080:80

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            PMA_HOSTS: "mysql-service"
            PMA_USER: "${MYSQL_USERNAME}"
            PMA_PASSWORD: "${MYSQL_PASSWORD}"
            PMA_ARBITRARY: 1